### ISSUE TITLE
Copy settings.sample.py to where

### ISSUE THREAD

**Issue by ZuoHaoyu** [hrishikeshrt/sangrahaka#1]
Hi Hrishikesh!

Conratualtions on your work.

I'm following the guidance to have a test of it but got stuck on the step:

"Copy settings.sample.py to settings.py and make appropriate changes."

Could you please speicify more on where the settings.py is please? :-)

Best,
HY

**Comment by hrishikeshrt** [comment]
Thank you!

You create the `settings.py` file by making a copy of the `settings.sample.py` file (right beside it, in the same folder).
It holds settings such as the secret key for Flask application, the path to the database and so on.

**Comment by ZuoHaoyu** [comment]
Thanks Hrishikesh!
