### ISSUE TITLE
How to generate the Corpus in the specified data format?

### ISSUE THREAD

**Issue by jeevan-exa** [hrishikeshrt/sangrahaka#2]
We are very curious to know how to convert a text corpus into the format that is being used. Please provide some pointers on how to do it

**Comment by jeevan-exa** [comment]
We found it under examples/epic/corpus. Thanks

**Comment by hrishikeshrt** [comment]
Glad that you found it. 

The overall format, along with other necessary details, is explained in the `examples/README.md`

Entries inside `"tokens"` key (which in turn is a subkey of `"analysis"`), are what get displayed in a tabular manner in the Corpus Viewer interface. Every `token` is essentially a dictionary containing any relevant information, and can contain arbitrary keys as long as all the tokens have the same keys.
