### ISSUE TITLE
Database Creation Error

### ISSUE THREAD

**Issue by trinity999** [hrishikeshrt/sangrahaka#4]
After extraction of neo4j and Sangrahaka in C:\ and respective requirement installation I faced an error. After initializing neo4j and server_sqla.py . As stated when I go to http://localhost:5000. I get an error stating sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file. Do I need to do any changes in directory to avoid the error??

**Comment by gsabarinath02** [comment]
if you were able to resolve this, please let me know

**Comment by hrishikeshrt** [comment]
Please create a directory "db" in the base directory and restart the server.
